### ISSUE TITLE
Debug mode (or more information at least)

### ISSUE THREAD

**Issue by p0nch0d3v** [js13kGames/js-game-server#1]
Is there a way to enable more debug (or include more info) when the games are running in this server ?, i mean, if i forget put some semicolon, or use incorrectly a variable, or put some malformed code, or use a non declared function (by mistake or misspelling), or forget put a curly bracket, etc, because it is little annoying to try to find or guess where the error is (because no error in the log console, just the site is not up), in a few words, i am requesting more debug/error info when the server is running, without i modified the code of this server.

Thanks

**Comment by ArkahnX** [comment]
Hey, its a bit late, but I modified line 55 of lib/sandboxer.js from
`log.error('Game fail', err, {game: game.codeName});`
to
`log.error('Game fail', err, err.stack, {game: game.codeName});`

err.stack gives you the nice waterfall of where things went wrong, usually the files that are relevant to you are near the top of the waterfall.

**Comment by aurium** [comment]
For the next year we will have an admin interface were we will see game status and some helpful information for devs and server admins.

**Comment by p0nch0d3v** [comment]
@aurium Thanks !
